{{- $saName := (include "codedx-tool-orchestration.serviceAccountName" .) | quote -}}
{{- $rName := (printf "%s-%s" (include "codedx-tool-orchestration.fullname" .) "role") | quote -}}
{{- $rbName := (printf "%s-%s" (include "codedx-tool-orchestration.fullname" .) "binding") | quote -}}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $saName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
---
{{ end -}}


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $rName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows"]
  verbs: ["get", "list", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings"]
  verbs: ["create"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles"]
  verbs: ["bind"]
  resourceNames: [{{ include "codedx-tool-orchestration.workflow.role.name" . | quote }}]
{{- if .Values.podSecurityPolicy.tws.bind }}
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "codedx-tool-orchestration.rbac.psp.tws.name" . | quote }}
{{- end }}
---


apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "codedx-tool-orchestration.workflow.role.name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "patch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "watch"]
{{- if .Values.podSecurityPolicy.twsWorkflows.bind }}
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "codedx-tool-orchestration.rbac.psp.tws-workflows.name" . | quote }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $rbName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $rName }}
subjects:
- name: {{ $saName }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
{{- if .Values.podSecurityPolicy.argo.bind }}
---


{{- $argoRoleName := (include "sanitize" (printf "%s-argo-use-psp" (include "codedx-tool-orchestration.fullname" .))) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $argoRoleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "codedx-tool-orchestration.rbac.psp.argo.name" . }}
---


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $argoRoleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $argoRoleName | quote }}
subjects:
- name: {{ .Values.argo.controller.serviceAccount | quote }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}
{{- if and .Values.minio.enabled .Values.podSecurityPolicy.minio.bind }}
---
{{- $minioRoleName := (include "sanitize" (printf "%s-minio-use-psp" (include "codedx-tool-orchestration.fullname" .))) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $minioRoleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "codedx-tool-orchestration.rbac.psp.minio.name" . }}
---


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $minioRoleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx-tool-orchestration.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $minioRoleName | quote }}
subjects:
- name: {{ include "minio.ref.serviceAccountName" . }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}
