apiVersion: v1
kind: Service
metadata:
  name: {{ include "codedx.servicename" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
  annotations:
{{ toYaml $.Values.service.annotations | trim | indent 4 }}
spec:
  type: {{ include "codedx.servicetype" . }}
  ports:
  - protocol: TCP
  {{- if .Values.codedxTls.componentEnabled }}
    targetPort: 8443
  {{- else }}
    targetPort: 8080
  {{- end }}
  {{- if .Values.codedxTls.serviceEnabled }}
    name: https
    port: {{ .Values.codedxTlsTomcatPort }}
  {{- else }}
    name: http
    port: {{ .Values.codedxTomcatPort }}
  {{- end }}
  selector:
    app: {{ include "codedx.name" . | quote }}
    release: {{ .Release.Name | quote }}
    component: frontend