{{- if .Values.ingress.enabled -}}
{{- range .Values.ingress.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx.commonLabels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
{{- if .key }}
  tls.key: {{ .key | trim }}
{{- end -}}

{{- if .certificate }}
  tls.crt: {{ .certificate | trim }}
{{- end }}
---
{{- end -}}
{{- end -}}