{{- if .Values.mariadb.enabled -}}
{{ if .Values.podSecurityPolicy.mariadb.bind }}
---
{{- $roleName := include "sanitize" (printf "%s-mariadb-use-psp" (include "codedx.fullname" .)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $roleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
rules:
- apiGroups: ["policy"]
  resources: ["podsecuritypolicies"]
  verbs: ["use"]
  resourceNames:
  - {{ include "codedx.rbac.psp.dbname" . | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $roleName | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "codedx.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $roleName | quote }}
subjects:
- name: {{ include "mariadb.ref.serviceAccountName" . | quote }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
{{- end -}}
{{- end -}}